# Generated by Django 6.1.1 on 2026-09-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('service', 'date', 'time'), name='unique_service_booking_slot'),
        ),
    ]
